create table "UXD".SESSIONS
(
	ID INTEGER not null primary key,
	VALUE VARCHAR(255),
	TIMESTAMP TIMESTAMP,
	SOURCENAME VARCHAR(255)
)

create table "UXD".BOUNCES
(
        ID INTEGER not null primary key,
	VALUE VARCHAR(255),
	TIMESTAMP TIMESTAMP,
	SOURCENAME VARCHAR(255)
)

create table "UXD".SOURCES
(
        SOURCENAME VARCHAR(255)
)